# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  # Coverage analysis settings
  status:
    # Status for overall project coverage
    project:
      default:
        # Target: 'auto' means Codecov automatically determines the target
        # based on the recent coverage history of the project
        target: 80%
        # Allow coverage to drop by this much before failing
        threshold: 1%
        # Only consider files matching these patterns
        paths:
          - "codeflow_engine/**"
        # Ignore missing coverage from these paths
        if_no_uploads: error
    # Status for changes in the PR (patch coverage)
    patch:
      default:
        # Target: 'auto' means Codecov automatically determines the target
        # based on the recent coverage history of the project
        target: 70%
        threshold: 1%
        if_no_uploads: success

# Ignore files that don't need coverage
ignore:
  - "tests/**"
  - "docs/**"
  - "examples/**"
  - "scripts/**"
  - "**/__pycache__/**"
  - "**/migrations/**"
  - "setup.py"

# Comment settings for PR comments
comment:
  # Layout of the comment
  layout: "header, diff, flags, components"
  # Behavior for comments
  behavior: default
  # Require at least this many builds before commenting
  require_changes: false
  # Include base report in the comment
  require_base: false
  # Include head report in the comment
  require_head: true

# Flags for different types of tests
flags:
  unittests:
    paths:
      - "codeflow_engine/**"
    carryforward: true

# GitHub-specific configuration
github_checks:
  annotations: true
