"""
Platform Detection Patterns

Pattern definitions for different rapid prototyping platforms.
"""

from typing import Any


class PlatformPatterns:
    """Platform-specific detection patterns."""

    @staticmethod
    def get_platform_signatures() -> dict[str, dict[str, Any]]:
        """Get platform signature patterns."""
        return {
            "replit": {
                "files": [".replit", "replit.nix", "pyproject.toml", ".replit.json"],
                "package_scripts": ["repl-run", "replit-dev", "repl-dev"],
                "commit_patterns": [
                    "replit",
                    "exported from replit",
                    "repl.it",
                    "from replit",
                ],
                "dependencies": ["@replit/database", "replit-py"],
                "folder_patterns": [".replit_modules", "replit_modules"],
                "content_patterns": ["replit.com", "repl.co"],
            },
            "lovable": {
                "files": ["lovable.config.js", ".lovable", "lovable.json"],
                "dependencies": ["@lovable/core", "lovable-ui", "@lovable/cli"],
                "commit_patterns": ["lovable", "generated by lovable", "lovable.dev"],
                "package_scripts": ["lovable:dev", "lovable:build", "lovable:deploy"],
                "content_patterns": ["lovable.dev", "generated with lovable"],
                "folder_patterns": [],
            },
            "bolt": {
                "files": ["bolt.config.json", ".bolt", "bolt.json", ".bolt.config"],
                "package_scripts": ["bolt:dev", "bolt:build", "bolt:start"],
                "commit_patterns": ["bolt.new", "bolt generated", "created with bolt"],
                "dependencies": ["@bolt/core", "bolt-cli"],
                "content_patterns": ["bolt.new", "built with bolt"],
                "folder_patterns": [],
            },
            "same": {
                "files": ["same.config.js", ".same", "same.json"],
                "commit_patterns": ["same.new", "cloned from same", "same template"],
                "dependencies": ["@same/core", "same-cli"],
                "package_scripts": ["same:dev", "same:clone", "same:customize"],
                "content_patterns": ["same.new", "cloned with same"],
                "folder_patterns": [],
            },
            "emergent": {
                "files": [
                    "emergent.sh",
                    ".emergent",
                    "deploy.emergent",
                    ".emergent.yml",
                ],
                "commit_patterns": [
                    "emergent.sh",
                    "automated by emergent",
                    "emergent deploy",
                ],
                "content_patterns": ["emergent.sh", "emergent automation"],
                "folder_patterns": ["emergent_scripts", ".emergent_cache"],
            },
            "riff_new": {
                "files": [],
                "dependencies": [],
                "commit_patterns": [],
                "package_scripts": [],
                "content_patterns": ["riff.new"],
                "folder_patterns": [],
            },
            "same_new": {
                "files": [],
                "dependencies": [],
                "commit_patterns": [],
                "package_scripts": [],
                "content_patterns": ["same.new"],
                "folder_patterns": [],
            },
            "bolt_new": {
                "files": [],
                "dependencies": [],
                "commit_patterns": [],
                "package_scripts": [],
                "content_patterns": ["bolt.new"],
                "folder_patterns": [],
            },
            "warp": {
                "files": [],
                "dependencies": [],
                "commit_patterns": [],
                "package_scripts": [],
                "content_patterns": [],
                "folder_patterns": ["~/.warp"],
            },
            "claude_code": {
                "files": [],
                "dependencies": ["@anthropic-ai/sdk"],
                "commit_patterns": [],
                "package_scripts": [],
                "content_patterns": [],
                "folder_patterns": [],
            },
            "cto_net": {
                "files": [],
                "dependencies": [],
                "commit_patterns": [],
                "package_scripts": [],
                "content_patterns": ["cto.net"],
                "folder_patterns": [],
            },
            "factory_ai": {
                "files": [],
                "dependencies": [],
                "commit_patterns": [],
                "package_scripts": [],
                "content_patterns": ["factory.ai"],
                "folder_patterns": [],
            },
            "base44": {
                "files": [".base44", ".base44/config.json", "base44.config.js", ".base44.yaml"],
                "dependencies": ["@base44/core", "@base44/cli", "base44-sdk"],
                "commit_patterns": ["base44", "Base44", "generated by base44", "base44.ai"],
                "package_scripts": ["base44:dev", "base44:build"],
                "content_patterns": ["base44.ai", "base44 config", "powered by base44"],
                "folder_patterns": ["base44-", "-base44", ".base44"],
            },
            "windsurf": {
                "files": [".windsurf", ".windsurf/config.json", ".windsurfrules"],
                "dependencies": ["@codeium/windsurf", "windsurf-extension"],
                "commit_patterns": ["windsurf", "Windsurf", "codeium windsurf"],
                "content_patterns": ["windsurf", "codeium.com/windsurf"],
                "folder_patterns": ["windsurf-", "-windsurf", ".windsurf"],
            },
            "continue": {
                "files": [".continue", ".continue/config.json", ".continue/config.yaml", ".continuerules"],
                "dependencies": ["continue-dev", "@continue/sdk"],
                "commit_patterns": ["continue", "Continue", "continue.dev"],
                "content_patterns": ["continue.dev", "continue config"],
                "folder_patterns": ["continue-", "-continue", ".continue"],
            },
            "aider": {
                "files": [".aider", ".aider.conf.yml", ".aider.input.history", ".aider.chat.history.md"],
                "dependencies": ["aider-chat"],
                "commit_patterns": ["aider", "Aider", "aider.chat", "aider:"],
                "content_patterns": ["aider.chat", "aider config"],
                "folder_patterns": [".aider", "aider-"],
            },
            "amazon_q": {
                "files": [".amazonq", ".aws/amazonq", ".vscode/amazonq.json"],
                "dependencies": ["@aws/amazonq", "amazon-q-developer"],
                "commit_patterns": ["amazon q", "Amazon Q", "amazonq"],
                "content_patterns": ["amazon q", "aws.amazon.com/q"],
                "folder_patterns": ["amazonq-", "-amazonq"],
            },
            "google_ai_studio": {
                "files": [".google-ai", ".google-ai-studio", "google-ai.config.json"],
                "dependencies": ["@google/generative-ai", "google-ai-sdk"],
                "commit_patterns": ["google ai", "Google AI Studio", "gemini"],
                "content_patterns": ["ai.google.dev", "google ai studio"],
                "folder_patterns": ["google-ai-", "-google-ai"],
            },
            "huggingface_code": {
                "files": [".huggingface", ".hf", "huggingface.config.json"],
                "dependencies": ["@huggingface/inference", "transformers"],
                "commit_patterns": ["hugging face", "Hugging Face", "huggingface"],
                "content_patterns": ["huggingface.co", "hf hub"],
                "folder_patterns": ["huggingface-", "-huggingface", ".hf"],
            },
            "codegpt": {
                "files": [".codegpt", ".vscode/codegpt.json", "codegpt.config.json"],
                "dependencies": ["codegpt-vscode", "@codegpt/sdk"],
                "commit_patterns": ["codegpt", "CodeGPT", "code gpt"],
                "content_patterns": ["codegpt.co", "codegpt config"],
                "folder_patterns": ["codegpt-", "-codegpt"],
            },
            "phind": {
                "files": [".phind", "phind.config.json"],
                "dependencies": ["phind-sdk", "@phind/api"],
                "commit_patterns": ["phind", "Phind", "phind.com"],
                "content_patterns": ["phind.com", "phind search"],
                "folder_patterns": ["phind-", "-phind"],
            },
            "supermaven": {
                "files": [".supermaven", ".supermaven/config.json"],
                "dependencies": ["supermaven", "@supermaven/sdk"],
                "commit_patterns": ["supermaven", "Supermaven"],
                "content_patterns": ["supermaven.com", "supermaven config"],
                "folder_patterns": ["supermaven-", "-supermaven"],
            },
        }

    @staticmethod
    def get_advanced_patterns() -> dict[str, dict[str, Any]]:
        """Get advanced detection patterns."""
        return {
            "replit": {
                "readme_patterns": ["run on replit", "replit button", "repl.it"],
                "env_patterns": ["REPL_ID", "REPL_OWNER", "REPL_SLUG"],
                "dockerfile_patterns": ["replit/polygott", "replit run"],
            },
            "lovable": {
                "readme_patterns": ["built with lovable", "lovable.dev"],
                "component_patterns": ["lovable-component", "@lovable/"],
            },
            "bolt": {
                "readme_patterns": ["bolt.new", "built with bolt"],
                "api_patterns": ["bolt api", "bolt endpoint"],
            },
        }
